#!/bin/bash

USER_GCLOUD_AUTHED=
DNS_ZONE=
DNS_RECORD_NAME=
DNS_RECORD_TYPE=
DNS_RECORD_TTL=
PATH_TRANSACTION=/tmp

# Checks for dig and gcloud
if [[ ! $(command -v dig) ]] || [[ ! $(command -v gcloud) ]]; then
  echo Error: gcloud-dns-update requires dig and gcloud 
  exit 1
fi

# Checks for required parameters
if [[ -z $USER_GCLOUD_AUTHED ]] || [[ -z $DNS_ZONE ]] || [[ -z $DNS_RECORD_NAME ]] || [[ -z $DNS_RECORD_TYPE ]] || [[ -z $DNS_RECORD_TTL ]] || [[ -z $PATH_TRANSACTION ]]; then
  echo Error: gcloud-dns-update has missing parameters 
  exit 1
fi

# Re-executes this as the user authenticated via gcloud
if [[ $(id -u) -eq 0 ]]; then
  exec sudo -H -u $USER_GCLOUD_AUTHED $0 "$@"
fi

DNS_RECORD_OLDDATA=$(gcloud dns record-sets list --zone=$DNS_ZONE --name=$DNS_RECORD_NAME --type=$DNS_RECORD_TYPE | grep $DNS_RECORD_NAME | xargs | cut -d\  -f4)
DNS_RECORD_NEWDATA=$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | xargs)
DEFAULT="--zone=$DNS_ZONE --transaction-file=$PATH_TRANSACTION/gcloud-dns-transaction-$(date +%s).yaml"

gcloud dns record-sets transaction start $DEFAULT 
gcloud dns record-sets transaction remove $DEFAULT --name=$DNS_RECORD_NAME --type=$DNS_RECORD_TYPE --ttl=$DNS_RECORD_TTL $DNS_RECORD_OLDDATA
gcloud dns record-sets transaction add $DEFAULT --name=$DNS_RECORD_NAME --type=$DNS_RECORD_TYPE --ttl=$DNS_RECORD_TTL $DNS_RECORD_NEWDATA 
gcloud dns record-sets transaction execute $DEFAULT 
